# using the pin base image of the version
# thats why the addition of @sha[...]
# FROM alpine@sha256:4bcff63911fcb4448bd4fdacec207030997caf25e9bea4045fa6c8c44de311d1
# the above version is the latest
# below is the correct to be used
FROM alphine@sha256:b6a6be0ff92ab6db8acd94f5d1b7a6c2f0f5d10ce3c24af348d333ac6da80685
# for alpine using the no cache option
# first command done after finishing run
RUN apk add --no-cache mariadb
CMD ["mysqld"]