services:
  mariadb:
    # first setting the directory path
    # then specify my own name for Dockerfile
    build:
      context: ./req/mariadb
      dockerfile: Dockerfile_db
    # tagging the image as mariadb
    # and setting the container name
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    # changing the default directory
    # rather than using /var/lib/mysql
    # command is to set that path for db
    volumes:
      - mariadb:/var/db
    command: --datadir=/var/db
    # always restart if container stops
    restart: always

volumes:
  mariadb:
    name: mariadb
    # the volume is localy saved on the host
    # set to false as it needs to be created
    driver: local
    external: false
    # 1st option is setting where volume is
    # 2nd to access files from container and host
    # 3rd none as there is no disk partition
    driver_opts:
      device: "/home/ndziadzi/data/mariadb"
      o: bind
      type: none


networks:
  inception:
    name: inception
