# specify the version to use network and services
# its obsolete for this version of docker
# version: "3"
# ----------------
# all the services
# ----------------
services:
  mariadb:
    # first setting the directory path
    # then specify my own name for Dockerfile
    build:
      context: ./req/mariadb
      dockerfile: Dockerfile_db
    # tagging the image as mariadb
    # and setting the container name
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    # changing the default directory
    # rather than using /var/lib/mysql
    # command is to set that path for db
    # redone to the base because of problems
    volumes:
      - mariadb:/var/lib/mysql
    # always restart if container stops
    # the env file to be used by services
    restart: always
    env_file:
      - path: ./.env
        required: true
    # adding the part to do a healthcheck
    # as per later on in the dependencies
    healthcheck: 
      test: mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASS} | grep alive
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  # -----------------------------------
  # second service that I am setting up
  # -----------------------------------
  wordpress:
    build:
      context: ./req/wordpress
      dockerfile: Dockerfile_wp
    image: wordpress
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    restart: always
    env_file:
      - path: ./.env
        required: true
    # new part of the service setup
    # controlling order of startup
    # running extra healthcheck
    # without it just checks if started
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 5s
  # -----------------------------------
  # combining with nginx the above ones
  # -----------------------------------
  nginx:
    build:
      context: ./req/nginx
      dockerfile: Dockerfile_nginx
    image: nginx
    container_name: nginx
    networks:
      - inception
    restart: always
    depends_on:
      wordpress:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/html
    # setting up the communication
    # exposing the port of access
    ports:
      - "443:443"
# -----------------------
# persistent data storage
# -----------------------
volumes:
  mariadb:
    name: mariadb
    # the volume is localy saved on the host
    # set to false as it needs to be created
    driver: local
    external: false
    # 1st option is setting where volume is
    # 2nd to access files from container and host
    # 3rd none as there is no disk partition
    driver_opts:
      device: "/home/ndziadzi/data/mariadb"
      o: bind
      type: none
  # ---------------------------
  # second volume for wordpress
  # ---------------------------
  wordpress:
    name: wordpress
    driver: local
    external: false
    driver_opts:
      device: "/home/ndziadzi/data/wordpress"
      o: bind
      type: none
# ------------------------
# establishing connections
# ------------------------
networks:
  inception:
    name: inception
